[package]
name = "lila-socket"
version = "0.1.0"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
edition = "2018"

[dependencies]
websocket = "0.22.4"
tokio = "0.1.21"
futures = "0.1.28"
cookie = "0.12.0"
mongodb = "0.3.12"
serde_urlencoded = "0.5.5"
serde = { version = "1.0.94", features = ["derive"] }
redis-async = "0.4.5"
serde_json = "1.0.40"

